[package]
name = "interlock"
version = "0.0.0"
authors = ["yvt <i@yvt.jp>"]
license = "MIT/Apache-2.0"
edition = "2021"
readme = "README.md"
description = "Readers-writer locks optimized for locking intervals (work in progress)"
repository = "https://github.com/yvt/interlock-rs"

[dependencies]
